package com.gregorio.parking;

import java.awt.AlphaComposite;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.gregorio.parking.utils.ParseType;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Terminal extends javax.swing.JFrame {
    private static final Integer[][] parking=new Integer[3][20];
    private JTable tabla; //Control para mostrar la mastriz de enteros 
    private DefaultTableModel modeloTabla; //Contenedor de la matriz de enteros 
    private JTable tablaTicket; //Control para mostrar la mastriz de enteros 
    private DefaultTableModel modeloTablaTicket; //Contenedor de la matriz de enteros 
    public Maquina maquina;

    public Terminal(Maquina maquina) {
        // Atributos
        this.maquina = maquina;

        // Fondo global
        FondoPanel fondo = new FondoPanel("/background.jpg");
        this.setContentPane(fondo);

        // Inicio de componentes
        initComponents();
        // Fondo de ticket
        FondoPanel fondoTiket = new FondoPanel("/papel3.jpg");
        this.scroll_ticket.setViewportView(fondoTiket);

        // Lo centramos
        setLocationRelativeTo(null);
        setTitle("Parking Terminal");
        // Para inicializar con 0 (en vez de null), necesitas hacerlo manualmente
        for (int i = 0; i < parking.length; i++) {
            for (int j = 0; j < parking[i].length; j++) {
                parking[i][j] = 0;
                
            }
        }
        
        mostrarParking();
        this.generaticket.setEnabled(false);
        this.retirarvehiculo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitor = new javax.swing.JPanel();
        generaticket = new javax.swing.JButton();
        retirarvehiculo = new javax.swing.JButton();
        text_matricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        scroll_ticket = new javax.swing.JScrollPane();
        parking_esquema = new javax.swing.JScrollPane();
        deposito = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        monitor.setBorder(javax.swing.BorderFactory.createTitledBorder("Parking"));

        generaticket.setText("Generar Ticket");
        generaticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaticketActionPerformed(evt);
            }
        });

        retirarvehiculo.setText("Retirar Vehiculo");
        retirarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarvehiculoActionPerformed(evt);
            }
        });

        text_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_matriculaActionPerformed(evt);
            }
        });
        text_matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_matriculaKeyTyped(evt);
            }
        });

        jLabel1.setText("Matricula:");

        jLabel2.setText("ID:");

        text_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_idKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout monitorLayout = new javax.swing.GroupLayout(monitor);
        monitor.setLayout(monitorLayout);
        monitorLayout.setHorizontalGroup(
            monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monitorLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(55, 55, 55))
            .addGroup(monitorLayout.createSequentialGroup()
                .addGroup(monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monitorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(generaticket))
                    .addGroup(monitorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retirarvehiculo))
                    .addGroup(monitorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_matricula, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(text_id))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monitorLayout.setVerticalGroup(
            monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generaticket)
                .addGap(4, 4, 4)
                .addGroup(monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(retirarvehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll_ticket.setToolTipText("tickets");

        parking_esquema.setToolTipText("");

        deposito.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deposito)
                    .addComponent(parking_esquema)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scroll_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scroll_ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(parking_esquema, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Genera ticket, y lo almacena en la lista de tickets
     * 
     * @param evt Evento de tipo ActionEvent que se produce al hacer clic en el botón
     */
    private void generaticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaticketActionPerformed
        // Generar ticket
        
        // Ubicacion del coche (ubicacion)
        Ubicacion ubicacion = new Ubicacion(0,0);
        int id = 0;

        // Buscamos si hemos encontrado algun hueco libre
        boolean encontrado=false;
        for (int y = 0; y < parking.length && !encontrado; y++) {
            for (int x = 0; x < parking[y].length && !encontrado; x++) {
                if (parking[y][x] == 0) {
                    // Obtenemos la ubicacion y el id si hay plaza libre
                    ubicacion = new Ubicacion(y,x);
                    id = parking[y][x] = this.generarIdParking(x, y);
                    encontrado=true;
                }
            }
        }

        // Creamos el tiket correspondiente
        Ticket ticketmostrar=maquina.generarTiket(id, this.text_matricula.getText(), LocalDateTime.now(), ubicacion);
        mostrarParking();
        mostrarTicket(ticketmostrar);
    }//GEN-LAST:event_generaticketActionPerformed
    
    private int generarIdParking(int x,int y){
       return y*20+x+1; 
    }
    
    private void retirarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarvehiculoActionPerformed
        // Obtenemos el id del ticket
        Integer id = ParseType.parseInteger(this.text_id.getText());
        if(id == null){
            JOptionPane.showMessageDialog(
                this, 
                "Introduce un ID válido", 
                "Error de validación", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        } 
       
        // Obtenemos la fecha de salida
        String fechaInput = JOptionPane.showInputDialog("Introduce la fecha de salida (dd/MM/yyyy HH:mm:ss)");
        LocalDateTime fecha = ParseType.parseLocalDateTime(fechaInput);
        if(fecha == null){
            // Versión básica con icono de error y título
            JOptionPane.showMessageDialog(
                this, 
                "Introduce una fecha valida", 
                "Error de validación", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Buscamos el ticket en la lista de tickets por busqueda binaria
        ArrayList<Ticket> tickets = maquina.getTickets();
        double precioTicket = 0;
        Ticket selecionado = null;    
        for (Ticket ticket : tickets) {
            if (id == ticket.getId()) {
                precioTicket = maquina.caluclarPrecioTicket(ticket, fecha);
                selecionado = ticket;
                break;
            }
        }

        if(selecionado == null){
            JOptionPane.showMessageDialog(
                this, 
                "No se ha encontrado el ticket con esa i", 
                "Error de validación", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Cantidad que el usuario deve pagar
        JOptionPane.showMessageDialog(this, "   Pagar: " + precioTicket + "€");

        // Cantidad que el usuario paga
        String dineroUsuario = JOptionPane.showInputDialog("Introduce el dinero, en formato double (0.0)");
        Double dineroUsusario= ParseType.parseDouble(dineroUsuario);
        if(dineroUsuario == null || dineroUsusario < 0){
            JOptionPane.showMessageDialog(
                this, 
                "Introduce un valor valido",
                 "Error de validación", JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Pagamos en la maquina
        maquina.getDeposito().procesarPago(dineroUsusario, precioTicket);
        System.out.println(maquina.getDeposito());

        // Retiramos el viculo y actualizamos el array
        maquina.retirarVehiculo(selecionado);
        parking[selecionado.getUbicacion().getPlanta()-1][selecionado.getUbicacion().getPlaza()-1] = 0;

        // Actualizamos el array de coches
        mostrarParking();
    }//GEN-LAST:event_retirarvehiculoActionPerformed

    private void text_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_matriculaActionPerformed
       // TODO add your handling code here: 
    }//GEN-LAST:event_text_matriculaActionPerformed

    private void text_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idKeyTyped
        if (!this.text_id.getText().isEmpty() || evt.getKeyChar() != '\b') 
            this.retirarvehiculo.setEnabled(true);
        else 
            this.retirarvehiculo.setEnabled(false);
    }//GEN-LAST:event_text_idKeyTyped

    private void text_matriculaKeyTyped(java.awt.event.KeyEvent evt) {
        if (!this.text_matricula.getText().isEmpty() || evt.getKeyChar() != '\b') 
            this.generaticket.setEnabled(true);
        else 
            this.generaticket.setEnabled(false);
    }//GEN-LAST:event_text_matriculaKeyTyped

    private void mostrarParking() {
        // Configuramos los títulos de las columnas del JTable
        String[] titulosColumnas = new String[parking[0].length];
        Arrays.fill(titulosColumnas, "");
        
        // Creamos el modelo de datos
        modeloTabla = new DefaultTableModel(parking, titulosColumnas);
        
        // Creamos el JTable con ese modelo
        tabla = new JTable(modeloTabla);
        
        // Ocultamos el encabezado 
        tabla.getTableHeader().setVisible(false);
        tabla.getTableHeader().setPreferredSize(new Dimension(0, 0));
        
        // Hacemos la tabla transparente para que se vea el fondo
        tabla.setOpaque(false);
        tabla.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        // Establecemos el tamaño de celda uniforme para mejor visualización
        tabla.setRowHeight(50);
        tabla.setRowMargin(20);
        // Creamos un renderer personalizado para colorear y centrar las celdas
        DefaultTableCellRenderer customRenderer = new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component cell = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                
                // Si la celda tiene un valor diferente de 0, la pintamos de verde
                if (value != null && !value.equals(0)) {
                    cell.setBackground(new java.awt.Color(144, 238, 144)); // Verde claro
                    cell.setForeground(java.awt.Color.BLACK); // Texto negro
                } else {
                    cell.setBackground(new java.awt.Color(0, 0, 0, 0)); // Transparente
                    cell.setForeground(java.awt.Color.BLACK);
                }
                
                return cell;
            }
        };
        
        // Centramos el texto
        customRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Aplicamos el renderer a todas las columnas
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(customRenderer);
        }

        // Añadimos la tabla al ScrollPane para que se muestre
        parking_esquema.setViewportView(tabla);
        
        // Para hacer como un refresco de la vista
        parking_esquema.revalidate();
        this.repaint();
    }
    
    private void mostrarTicket(Ticket ticket) {
        System.out.println("Ticket: " + ticket);
        Map<String, String> titulosList = new HashMap<>();
        titulosList.put("ID", String.valueOf(ticket.getId()));
        titulosList.put("Matricula", ticket.getMatricula());
        titulosList.put("Ubicación", ticket.getUbicacion().toString());
        // Fechas LocalDate
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        titulosList.put("Fecha Entrada", ticket.getFechaHoraEntrada().format(formatter));
         
        String[] titulos = new String[titulosList.size()];    
        
        int i = 0;
        for (String t : titulosList.keySet())
            titulos[i++] = t;
        
        String[][] contenidoTicket = new String[1][titulosList.size()];
        int index = 0;
        for (String key : titulosList.keySet()) 
            contenidoTicket[0][index++] = titulosList.get(key);
    
        // Creamos el modelo de datos
        modeloTablaTicket = new DefaultTableModel(contenidoTicket, titulos);
    
        // Creamos el JTable con ese modelo
        tablaTicket = new JTable(modeloTablaTicket);
        tablaTicket.getTableHeader().setPreferredSize(new Dimension(50, 35));
        // Center the header text
        ((DefaultTableCellRenderer) tablaTicket.getTableHeader().getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Hacemos la tabla transparente para que se vea el fondo
        tablaTicket.setOpaque(false);
        tablaTicket.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        // Creamos un panel transparente que contenga la tabla
        JPanel panelConTabla = new JPanel(new java.awt.BorderLayout());
        panelConTabla.setOpaque(false); // Panel transparente
        panelConTabla.add(tablaTicket.getTableHeader(), java.awt.BorderLayout.NORTH);
        panelConTabla.add(tablaTicket, java.awt.BorderLayout.CENTER);
        
        // Recuperamos el panel de fondo que ya está establecido
        FondoPanel fondoTicket = (FondoPanel) scroll_ticket.getViewport().getView();
        fondoTicket.setLayout(new java.awt.BorderLayout());
        
        // Limpiamos componentes anteriores y añadimos la nueva tabla
        fondoTicket.removeAll();
        fondoTicket.add(panelConTabla, java.awt.BorderLayout.CENTER);
        fondoTicket.revalidate();
        
        // Para hacer como un refresco de la vista
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane deposito;
    private javax.swing.JButton generaticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel monitor;
    private javax.swing.JScrollPane parking_esquema;
    private javax.swing.JButton retirarvehiculo;
    private javax.swing.JScrollPane scroll_ticket;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_matricula;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {
        private Image imagen;
        private boolean transparente = false;
        
        public FondoPanel(String imagePath) {
            this(imagePath, false);
        }
        
        public FondoPanel(String imagePath, boolean transparente) {
            try {
                
                this.transparente = transparente;
                java.net.URL url = getClass().getResource(imagePath);
                if(url != null)
                imagen = new ImageIcon(url).getImage();
                else 
                System.err.println("No se pudo cargar la imagen de fondo" + imagePath);
            } catch (Exception e) {
                System.out.println("Error al cargar la imagen de fondo: " + e.toString());
            }
        }
    
        @Override
        public void paint(Graphics g) {
            if (imagen != null) {
                if (transparente) {
                    // Dibuja con transparencia
                    Graphics2D g2d = (Graphics2D) g;
                    AlphaComposite alcom = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.3f); 
                    g2d.setComposite(alcom);
                    g2d.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                    g2d.setComposite(AlphaComposite.SrcOver);
                } else {
                    // Dibuja normal
                    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                }
            }
            setOpaque(false);
            super.paint(g);
        }
    }
}
